#!/usr/bin/env python3
"""Generate short vendor adapters from the versioned IntelliX templates."""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

import validate

GENERATED_MARKER = "<!-- Generated by IntelliX; edit the source template, not this file. -->"
ADAPTERS = {
    "framework/adapters/codex/AGENTS.md.template": "AGENTS.md",
    "framework/adapters/claude/CLAUDE.md.template": "CLAUDE.md",
}


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def rendered_adapters(source_root: Path, target_root: Path) -> dict[Path, str]:
    manifest_path = validate.resolve_contract_path(
        target_root, "intellix.yaml", "target project manifest", expect="file"
    )
    manifest = validate.load(manifest_path)
    if not isinstance(manifest, dict):
        raise validate.ValidationError("target intellix.yaml must be an object")
    framework_source = manifest.get("framework", {}).get("source")
    validate.resolve_contract_path(
        target_root,
        framework_source,
        "target framework.source",
        expect="file",
    )
    rendered: dict[Path, str] = {}
    for template_value, output_value in ADAPTERS.items():
        template = validate.resolve_contract_path(
            source_root, template_value, f"adapter template {template_value}", expect="file"
        )
        output = validate.resolve_contract_path(
            target_root,
            output_value,
            f"adapter output {output_value}",
            must_exist=False,
        )
        content = template.read_text(encoding="utf-8").replace(
            "{{framework_source}}", framework_source
        )
        if "{{" in content or "}}" in content:
            raise validate.ValidationError(f"{template}: unresolved template placeholder")
        rendered[output] = content
    return rendered


def generate(source_root: Path, target_root: Path, *, check: bool, force: bool) -> list[str]:
    errors: list[str] = []
    for output, expected in rendered_adapters(source_root, target_root).items():
        actual = output.read_text(encoding="utf-8") if output.exists() else None
        if check:
            if actual != expected:
                errors.append(f"{output}: generated adapter drift")
            continue
        generated = actual is not None and actual.startswith(GENERATED_MARKER + "\n")
        if actual is not None and actual != expected and not generated and not force:
            errors.append(
                f"{output}: refusing to overwrite a non-generated adapter; use --force explicitly"
            )
            continue
        atomic_write(output, expected)
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", required=True, type=Path)
    parser.add_argument("--target-root", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    try:
        source_root = validate.resolve_root(args.source_root)
        target_root = args.target_root.resolve(strict=True)
        if not target_root.is_dir():
            raise validate.ValidationError(f"target root is not a directory: {target_root}")
        errors = generate(
            source_root, target_root, check=args.check, force=args.force
        )
    except (OSError, validate.ValidationError) as exc:
        errors = [str(exc)]
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        print(f"FAILED: {len(errors)} adapter error(s)")
        return 1
    action = "valid" if args.check else "generated"
    print(f"OK: IntelliX project adapters are {action}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
